swagger: '2.0'
info:
  title: CouponLogger
  version: '1.0'
host: "localhost"
basePath: "/v1"
schemes:
  - https
  - http
paths:
  /couponLogger/{shopId}:
    get:
      tags:
        - "CouponLogger List By ShopId"
      summary: "获取优惠券使用"
      description: "获取优惠券使用"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "shopId"
        in: "path"
        description: "查看优惠券列表通过shopId"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CouponLoggerList"
        "405":
          description: "Invalid input"
  /couponLogger/{templateId}:
    get:
      tags:
        - "CouponLogger By Coupon TemplateId"
      summary: "获取具体优惠券使用"
      description: "获取具体优惠券使用"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "templateId"
        in: "path"
        description: "获取具体优惠券使用"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CouponLogger"
        "405":
          description: "Invalid input"

definitions:
  CouponLogger:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      shopId:
        type: "integer"
        format: "int64"
      templateId:
        type: "integer"
        format: "int64"
      title: 
        type: "string"
        format: "string"
      description:
        type: "string"
        format: "string"
      takeCount:
        type: "integer"
        format: "int64"
      remainCount:
        type: "integer"
        format: "int64"
      usedCount:
        type: "integer"
        format: "int64"

  CouponLoggerList:
    type: array
    items:
      $ref: "#/definitions/CouponLogger"