swagger: "2.0"
info:
  title: 订单结算API
  version: "1.0"
host: "localhost"
basePath: "/v1"
schemes:
  - https
  - http
paths:
  /cashier/confirm:
    post:
      tags:
        - "订单结算"
      summary: "订单确认"
      description: "订单确认"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "结算信息"
          required: true
          schema:
            $ref: "#/definitions/CashierRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
              msg:
                type: string
                format: string
              data:
                $ref: "#/definitions/CashierResponse"
        "405":
          description: "Invalid input"

  /cashier/checkout:
    post:
      tags:
        - "订单结算"
      summary: "下单"
      description: "下单"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "结算信息"
          required: true
          schema:
            $ref: "#/definitions/CashierRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
              msg:
                type: string
                format: string
              data:
                $ref: "#/definitions/CheckoutResponse"
        "405":
          description: "Invalid input"
  
  /cashier/pay:
    post:
      tags:
        - "订单结算"
      summary: "订单支付"
      description: "订单支付"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "支付订单ID"
          required: true
          type: "string"
          format: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int64
              msg:
                type: string
                format: string
              data:
                $ref: "#/definitions/PayResponse"
        "405":
          description: "Invalid input"

definitions:
  CashierRequest:
    type: "object"
    properties:
      trades:
        description: 交易物品信息
        type: array
        items:
          $ref: "#/definitions/CashierTradeRequest"
      delivery:
        description: 发货信息
        type: object
        properties:
          address:
            $ref: "#/definitions/Address"
      payment:
        description: 支付信息
        type: object
        properties:
          method:
            description: 支付方式
            type: integer
            format: int32
      ump:
        description: 营销信息
        type: object
        properties:
          coupons:
            description: 使用的优惠券
            type: array
            items:
              type: string
      source:
        description: 交易来源信息
        type: object
        properties:
          platform:
            description: 平台
            type: string
            format: string
          platformAppId:
            description: 平台AppId
            type: string
            format: string

  CashierTradeRequest:
    type: "object"
    properties:
      shopId:
        type: "integer"
        format: "int64"
        description: 店铺ID
      remark:
        description: 备注
        type: string
        format: string
      items:
        description: 商品列表
        type: array
        items:
          $ref: "#/definitions/CashierTradeItemRequest"
      ump:
        type: object
        properties:
          coupons:
            description: 使用的店铺优惠券列表
            type: array
            items:
              type: string

  CashierTradeItemRequest:
    type: object
    properties:
      skuId:
        type: "integer"
        format: "int64"
        description: 规格ID
      productId:
        type: "integer"
        format: "int64"
        description: 商品ID
      quantity:
        type: "integer"
        format: "int64"
        description: 数量

  CashierResponse:
    type: "object"
    properties:
      trades:
        description: 交易物品信息
        type: array
        items:
          $ref: "#/definitions/CashierTradeResponse"
      delivery:
        type: object
        properties:
          address:
            $ref: "#/definitions/Address"
      payment:
        description: 支付信息
        type: object
        properties:
          methodOptions:
            description: 支付方式选项
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  format: string
                  description: 支付方式名称
                value:
                  type: integer
                  format: int32
                  description: 支付方式
          method:
            description: 选择的支付方式
            type: integer
            format: int32
          total:
            description: 总价
            type: integer
            format: int64
          discount:
            description: 总优惠
            type: integer
            format: int64
          postage:
            description: 邮费
            type: integer
            format: int64
          final:
            description: 应支付金额
            type: integer
            format: int64
      ump:
        description: 营销信息
        type: object
        properties:
          coupons:
            description: 平台优惠券列表
            type: array
            items:
              $ref: "#/definitions/Coupon"

  CashierTradeResponse:
    type: "object"
    properties:
      shop:
        description: 店铺信息
        $ref: "#/definitions/SimpleShop"
      remark:
        description: 用户备注
        type: string
        format: string
      items:
        description: 商品列表
        type: array
        items:
          $ref: "#/definitions/CashierTradeItemResponse"
      payment:
        description: 价格信息
        $ref: "#/definitions/CashierTradePaymentResponse"
      ump:
        description: 营销信息
        type: object
        properties:
          coupons:
            description: 店铺优惠券列表
            type: array
            items:
              $ref: "#/definitions/Coupon"

  CashierTradePaymentResponse:
    description: 交易金额信息
    type: object
    properties:
      total:
        description: 总金额
        type: integer
        format: int64
      discount:
        description: 优惠金额
        type: integer
        format: int64
      postage:
        description: 运费
        type: integer
        format: int64
      final:
        description: 应支付金额：final = total - discount + postage
        type: integer
        format: int64

  CashierTradeItemResponse:
    type: object
    properties:
      productId:
        type: "integer"
        format: "int64"
        description: 商品ID
      skuId:
        type: "integer"
        format: "int64"
        description: 规格ID
      type:
        type: "integer"
        format: "int64"
        description: 类型
      title:
        description: 商品标题
        type: string
        format: string
      specs:
        description: 商品规格描述
        type: string
        format: string
      price:
        description: 商品单价
        type: "integer"
        format: "int64"
      discountPrice:
        description: 优惠后单价
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int64"
        description: 数量
      image:
        description: 商品图片
        type: string
        format: string
      stock:
        description: 库存量
        type: integer
        format: int32

  CashierPaymentResponse:
    type: object
    properties:
      total:
        description: 总价
        type: integer
        format: int64
      discount:
        description: 总优惠
        type: integer
        format: int64
      postage:
        description: 邮费
        type: integer
        format: int64
      originPostage:
        description: 原始邮费
        type: integer
        format: int64
      final:
        description: 应支付金额
        type: integer
        format: int64

  Coupon:
    type: object
    properties:
      id:
        type: "integer"
        format: "int64"
        description: 优惠券ID
      userId:
        type: "integer"
        format: "int64"
        description: 用户ID
      templateId:
        type: "integer"
        format: "int64"
        description: 券模版ID
      description:
        type: "string"
        format: "string"
        description: 描述
      title:
        type: "string"
        format: "string"
        description: 标题
      available:
        type: "boolean"
        format: "boolean"
        description: 是否可用
      selected:
        type: "boolean"
        format: "boolean"
        description: 是否已选
      channel:
        type: string
        format: string
        description: 领取渠道
      takeTime:
        type: "integer"
        format: "int64"
        description: 领取时间戳(ms)
      startTime:
        type: "integer"
        format: "int64"
        description: 使用开始时间戳(ms)
      endTime:
        type: "integer"
        format: "int64"
        description: 使用结束时间戳(ms)
      thresholdAmount:
        type: integer
        format: int64
        description: 使用门槛金额（满xxx），单位：分
      overlay:
        type: boolean
        format: boolean
        description: 是否允许叠加，即每满xxx
      discountAmount:
        type: integer
        format: int64
        description: 优惠金额（减xxx），单位：分
      maxDiscountAmount:
        type: integer
        format: int64
        description: 优惠金额上限（最多减xxx），单位：分

  SimpleShop:
    type: object
    description: 店铺概要信息
    properties:
      id:
        type: "integer"
        format: "int64"
        description: 店铺ID
      name:
        type: string
        format: string
        description: 名称
      avatar:
        type: string
        format: string
        description: 头像

  Address:
    type: object
    properties:
      id:
        description: 地址ID
        type: integer
        format: int64
      userId:
        description: 用户ID
        type: integer
        format: int64
      name:
        description: 收件人
        type: string
        format: string
      tel:
        description: 联系电话
        type: integer
        format: int64
      postalCode:
        description: 邮编
        type: integer
        format: int64
      province:
        description: 省
        type: string
        format: string
      city:
        description: 市
        type: string
        format: string
      district:
        description: 县/区
        type: string
        format: string
      address:
        description: 具体地址（具体的门牌号）
        type: string
        format: string

  CheckoutResponse:
    type: object
    properties:
      payOrderId:
        type: string
        format: string
        description: 支付订单ID
      orderIds:
        type: array
        items:
          type: string
          format: "string"
          description: 订单ID

  PayResponse:
    type: object
    properties: 
      method:
        type: string
        format: string
        description: 支付方式
      params:
        type: object
        description: 支付参数
      
